import type { Metadata } from "next";
/*import {
  ClerkProvider
} from '@clerk/nextjs'*/
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar"
import { AppSidebar } from "./(routes)/(root)/components";
import { Footer, Navbar } from "@/components/Shared";
import { ThemeInit } from "@/components/ThemeInit";


const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Sistema de gestion de recursos humanos",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {

  //quite clerkProvider
  return (
    
      <html lang="en" className={`${spaceGrotesk.variable} antialiased`}>
        <body className="transition-colors duration-300">
          <ThemeInit />
          <SidebarProvider>
            <AppSidebar />
            <div className="w-full bg-stone-100 flex flex-col min-h-screen">
              <Navbar />

              <main className="flex-1">{children}</main>

              <Footer />
            </div>
          </SidebarProvider>
        </body>
      </html>
    
  );
}

